"""
-> Introdução à Atividade sobre Loops (fof e while) com Hemoglobina.
A hemoglobina é uma proteína fundamental para a vida de muitos organismos, sendo responsável pelo 
transporte eficiente de oxigênio dos pulmões para os tecidos e pela remoção de dióxido de carbono. 
Sua função é crítica para processos fisiológicos essenciais, como a respiração e o metabolismo celular. 
Em humanos e outros mamíferos, a hemoglobina é composta por quatro subunidades: duas alfa e duas beta. 
Cada subunidade contém um grupo heme que se liga ao oxigênio, permitindo o transporte dessa molécula vital.

Nesta atividade, iremos explorar as sequências de subunidades de hemoglobina de diferentes e
spécies: Homo sapiens (humano), Felis catus (gato) e Mus musculus (camundongo). Essas subunidades, apesar 
de compartilharem funções semelhantes, possuem diferenças nas suas sequências que podem estar relacionadas 
a variações evolutivas e adaptações específicas de cada organismo.

A análise comparativa dessas sequências nos permite compreender melhor como as estruturas de proteínas 
se conservam ao longo da evolução e como pequenas variações podem afetar a função ou a eficiência dessas 
moléculas em diferentes espécies. Além disso, essa atividade oferece uma oportunidade de aplicar ferramentas 
bioinformáticas para analisar similaridades, diferenças e o significado biológico dessas variações.

Seguem abaixo as três sequências em uma string definida como a variável e 'sequencias'.

"""

sequencias ="""
>sp|P69905|HBA_HUMAN Hemoglobin subunit alpha OS=Homo sapiens OX=9606 GN=HBA1 PE=1 SV=2
MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHG
KKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTP
AVHASLDKFLASVSTVLTSKYR
>sp|P07412|HBB_FELCA Hemoglobin subunit beta-A/B OS=Felis catus OX=9685 GN=HBB PE=1 SV=1
GFLTAEEKGLVNGLWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSSADAIMSNAKV
KAHGKKVLNSFSDGLKNIDDLKGAFAKLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGH
DFNPQVQAAFQKVVAGVANALAHKYH
>sp|P02104|HBE_MOUSE Hemoglobin subunit epsilon-Y2 OS=Mus musculus OX=10090 GN=Hbb-y PE=1 SV=2
MVNFTAEEKTLINGLWSKVNVEEVGGEALGRLLVVYPWTQRFFDSFGNLSSASAIMGNPR
VKAHGKKVLTAFGESIKNLDNLKSALAKLSELHCDKLHVDPENFKLLGNVLVIVLASHFG
NEFTAEMQAAWQKLVAGVATALSHKYH
"""

# 1 - Usando as ferramentas de manipulação de string:
# a) Separe as sequências, sem o cabeçalho, em três listas independentes dentro de outra lista. Ex.: [[], [], []] 

# b) Imprima as três sequências com a estrutura de repetição.

# c) Imprima apenas a sequência de Humano e Rato usando repetição (for ou while). 


# 2 - Utilizando as sequências separadas dentro da outra lista, faça:
# a) loop para contar o número de aminoácidos (letras) em cada sequência e imprimir. Ex.: A sequência Hemoglobina de gato tem n aminoácidos. 

# b) Caso as sequências tenham tamanhos diferentes, deixe-as do mesmo tamanho, "cortando" o final da mesma. 

# c) Imprima em um loop as sequencias com mesmo tamanho. 


# DESAFIO:
# Identifique, usando loop e condicionais, quais regiões são conservadas (idênticas) 
# dentro das sequências, mesmo que não estejam na mesma posição. 
# Ex.: a sequência "HVD" está em todas as sequências, mas em posições diferentes. 

