sequencia="MKYSLLLFLAPLGVWSRACTCGQANQNGAYSRNENVIPRAENADEMLDRRDVHDGLAEKRDDLYARLINGKPTGLHEYPFIAAVVYNSGAKRISCPGAIIDKKHILITAHCVNGIRANNIGVYAGSNKFDVPSAKLRTVAAIHPHPKWDSERRFYDVALLQLQDPLSFDRNTNIVCVPSQPRDFNNQTATALAWGSSGEGQLVQTKFETHNLDSCSVRGTGGPQFCTYAPGEGVCDNASDGPLLLWQEPTSRRYFAVGLSSWGQSCKKFPEVATDLTQLKPWIQEVVGAGGGTLC"
ll_count = sequencia.count('LL')
wg_count = sequencia.count('WG')
print("LL: " + str(ll_count))
print("WG: " + str(wg_count))
print(sequencia.replace("RR", "EE"))
print(sequencia)
print(len(sequencia))
aminoacidos= 295/3
print(sequencia)
padrao= "PHP"
print(sequencia.split(padrao))